Update pre-commit steps and abort error message

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,27 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
+RED='\033[0;31m'
+YELLOW='\033[1;33m'
+GREEN='\033[0;32m'
+NC='\033[0m' # No Color
 
+set +e
 npm test
+if [ $? -eq 1 ]; then
+  echo $?
+  printf "${RED}ERROR: testing failed\n${NC}"
+  exit 1
+fi
 rm -rf test-results
+printf "${GREEN}Testing Passed\n${NC}\n"
+
 npm run prettier
-npm run eslint 
+printf "${YELLOW}WARNING: please commit the formated files if there is any\n${NC}"
+npm run eslint
+if [ $? -eq 1 ]; then
+  echo "ERROR: linting failed"
+  exit 1
+fi
+printf "${GREEN}Eslint Passed\n${NC}"
+
+exit 0;
